@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mod.traister101.sacks.objects.inventory.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;